[cluster]
name = "gravity-devnet"
base_dir = "/tmp/gravity-cluster"


[build]
binary_path = "../target/quick-release/gravity_node"

# 4-Node Cluster Configuration

[[nodes]]
id = "node1"
host = "127.0.0.1"
p2p_port = 6180
rpc_port = 8545
metrics_port = 9001

