# Gravity Bench E2E Test Configuration
contract_config_path = "deploy.json"
target_tps = 100
nodes = [
    { rpc_url = "http://localhost:8545", chain_id = 7771625 },
]
num_tokens = 1
enable_swap_token = false
address_pool_type = "random"

[faucet]
private_key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
faucet_level = 0
wait_duration_secs = 1
fauce_eth_balance = "1000000000000000000000000000000000"

[accounts]
num_accounts = 100

[performance]
num_senders = 10
max_pool_size = 1000
duration_secs = 300
sampling = 100

log_path = ""
